model:
    arch: dilated_fcn8s
    lower_dim: True
    weighted_mask: False
    use_norm: False
    offsetting: False
    use_scale: False
data:
    dataset: pascal_ignore
    n_classes: 20 
    ignore: 'bottle'
    train_split: train_aug
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: /home/menna/Datasets/VOCdevkit/VOC2012/
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 500
    n_workers: 1
    print_interval: 50
    optimizer:
        name: 'rmsprop'
        lr: 1.0e-6
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
        size_average: False
        pad: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
