model:
    arch: dilated_fcn8s
    lower_dim: True
    weighted_mask: False
    use_norm: False
    use_norm_weights: False
    offsetting: False
    use_scale: False
data:
    dataset: ivos
    n_classes: 4
    k_shot: 1
    img_rows: 500
    img_cols: 500
    path: /home/menna/Datasets/IVOS_dataset/
training:
    train_iters: 15
    batch_size: 1
    val_interval: 100000000
    n_workers: 1
    print_interval: 50
    optimizer:
        name: 'rmsprop'
        lr: 1.0e-4
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
