model:
    arch: dilated_fcn8s
    lower_dim: True
    weighted_mask: False
    use_norm: False
    offsetting: False
    use_scale: False
data:
    dataset: pascal5i
    fold: 0
    n_classes: 16
    k_shot: 1
    train_split: train_aug
    val_split: val
    img_rows: 500
    img_cols: 500
    path: /home/eren/Data/VOCdevkit/VOC2012
training:
    train_iters: 3000
    batch_size: 1
    val_interval: 50
    n_workers: 8
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 0.0025
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
        pad: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
