model:
    arch: reduced_fcn8s
    lower_dim: True
    weighted_mask: False
    use_norm: False
    use_norm_weights: False
    offsetting: False
    use_scale: False
data:
    dataset: pascal5i
    fold: 0
    n_classes: 16
    k_shot: 1
    train_split: train_aug
    val_split: val
    img_rows: 500
    img_cols: 500
    path: /home/menna/Datasets/VOCdevkit/VOC2012/
training:
    train_iters: 15
    batch_size: 1
    val_interval: 100000000
    n_workers: 1
    print_interval: 50
    optimizer:
        name: 'rmsprop'
        lr: 1.0e-4
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
    augmentations:
        hflip: 0.5                                     #[flip horizontally with chance p]
        vflip: 0.5                                     #[flip vertically with chance p]
#        ccrop: [300, 300]                                 #[center crop of (h,w)]
#        scale: [500, 500]                                 #[scale to size (h,w)]
#        gamma: x                                     #[gamma varied in 1 to 1+x]
#        hue: x                                       #[hue varied in -x to x]
#        brightness: x                                #[brightness varied in 1-x to 1+x]
#        saturation: x                                #[saturation varied in 1-x to 1+x]
#        contrast: x                                  #[contrast varied in 1-x to 1+x]
#        rcrop: [300, 300]                                #[crop of size (h,w)]
#        translate: [dh, dw]                          #[reflective translation by (dh, dw)]
#        rotate: d                                    #[rotate -d to d degrees]

